version: '3.6'

services:
    #redis:
      #restart: always
      #image: sameersbn/redis:4.0.9-2
      #command: 
         # - --loglevel warning
      #volumes:
         # - redis-data:/var/lib/redis:Z

    #db:
      #restart: always
      #image: launcher.gcr.io/google/postgresql10
      #volumes:
          #- ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
          #- ./backups/postrgresql:/backup
      #environment:
          #- POSTGRES_USER=admin
          #- POSTGRES_PASSWORD=gitlabadmin
          #- POSTGRES_DB=gitlabdb
      #container_name: database_gitlab
  
    web:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: localhost
      #environment:
        #GITLAB_OMNIBUS_CONFIG: |
          # external_url 'https://gitlab.example.com'
          #gitlab.rb
      ports:
        - '8080:80'
      volumes:
        - './gitlab/config:/etc/gitlab'
        - './gitlab/logs:/var/log/gitlab'
        - './gitlab/data:/var/opt/gitlab'
