version: '3.6'

services:    
    db:
        restart: always
        image: launcher.gcr.io/google/postgresql10
        volumes:
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./backups/postrgresql:/backup
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=gitlabadmin
            - POSTGRES_DB=gitlabdb

        networks:
            - gitlab
        container_name: database_gitlab
    web:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: localhost
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://gitlab.example.com'
          gitlab.rb
      ports:
        - '80:80'
          #- '443:443'
          #- '22:22'
      volumes:
        - '/srv/gitlab/config:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'
