version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:12.9.4-ce.0
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - 5122:22
      - 5180:80
    configs:
      - source: gitlab.rb
        target: /etc/gitlab/gitlab.rb
    networks:
      - default
      - gitlab_p2
    deploy:
      mode: replicated
      replicas: 1
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
  redis:
    image: redis:5.0.8-alpine
  postgres:
    image: postgres:11.7-alpine
    volumes:
      - postgres_data:/data
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - PGDATA=/data
  prometheus:
    image: prom/prometheus:v2.4.2
    command: "--config.file=/prometheus.yaml --storage.tsdb.path /data"
    volumes:
      - "prometheus_data:/data"
    configs:
      - prometheus.yaml
    networks:
      - default
      - gitlab_p2
    ports:
     - 5190:9090
    user: root:root
  grafana:
    image: grafana/grafana:6.7.3
    environment:
      GF_PATHS_CONFIG: "/grafana.ini"
    configs:
      - grafana.ini
    networks:
      - default
      - gitlab_p2
    ports:
      - 5130:3000

volumes:
  gitlab_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/gitlab_p2/gitlab/data
  gitlab_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/gitlab_p2/gitlab/config
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/gitlab_p2/postgres
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nfs/gitlab_p2/prometheus

configs:
  gitlab.rb:
    file: "./gitlab.rb"
  prometheus.yaml:
    file: "./prometheus.yml"
  grafana.ini:
    file: "./grafana.ini"

networks:
  gitlab_p2:
    external: true
