version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - 2222:22
      - 80:80
    configs:
      - source: gitlab.rb
        target: /etc/gitlab/gitlab.rb
    networks:
      - default
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gitlab.entrypoints=web
        - traefik.http.services.gitlab.loadbalancer.server.port=80
  redis:
    image: redis:5.0.8-alpine
  postgres:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/data
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      PGDATA: /data
      POSTGRES_DB: gitlab
  prometheus:
    image: prom/prometheus:v2.17.1
    command: "--config.file=/prometheus.yaml --storage.tsdb.path /data"
    volumes:
      - "prometheus_data:/data"
    configs:
      - prometheus.yaml
    networks:
      - default
      - proxy
    ports:
     - 9090:9090
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.prometheus.entrypoints=web
        - traefik.http.services.prometheus.loadbalancer.server.port=9090
  grafana:
    image: "grafana/grafana:5.4.3"
    environment:
      GF_PATHS_CONFIG: "/grafana.ini"
    configs:
      - grafana.ini
    volumes:
      - "grafana_data:/data"
    networks:
      - default
      - proxy
    ports:
      - 3000:3000
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.grafana.entrypoints=web
        - traefik.http.services.grafana.loadbalancer.server.port=3000

volumes:
  gitlab_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.85.141"
      device: ":/gitlab-swarm/gitlab/data"
  gitlab_logs:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.85.141"
      device: ":/gitlab-swarm/gitlab/logs"
  gitlab_config:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.85.141"
      device: ":/gitlab-swarm/gitlab/config"
  postgres_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.85.141"
      device: :/gitlab-swarm/postgres 
  prometheus_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.85.141"
      device: ":/gitlab-swarm/prometheus"
  grafana_data:
    driver: local
    driver_opts:
      type: nfs4
      o: "addr=192.168.85.141"
      device: ":/gitlab-swarm/grafana"

configs:
  gitlab.rb:
    file: "./gitlab.rb"
  prometheus.yaml:
    file: "./prometheus.yml"
  grafana.ini:
    file: "./grafana.ini"

networks:
  proxy:
    external: true
