version: "3.4"

services:
  gitlab:
    image: "gitlab/gitlab-ce:10.3.3-ce.0"
    volumes:
      - "gitlab_data:/var/opt/gitlab"
      - "gitlab_logs:/var/log/gitlab"
      - "gitlab_config:/etc/gitlab"
    ports:
      - "2222:22"
    configs:
      - source: "gitlab.rb"
        target: "/etc/gitlab/gitlab.rb"
    networks:
      - default
      - proxy
    deploy:
      labels:
        traefik.port: "80"
        traefik.frontend.rule: "Host:gitlab.localtest.me"
        traefik.docker.network: "proxy"

  redis:
    image: "redis:4.0.6-alpine"
  postgres:
    image: "postgres:10.1-alpine"
    volumes:
      - "postgres_data:/data"
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      PGDATA: /data
      POSTGRES_DB: gitlab
  prometheus:
    image: "prom/prometheus:v2.0.0"
    command: "--config.file=/prometheus.yaml --storage.tsdb.path /data"
    volumes:
      - "prometheus_data:/data"
    configs:
      - prometheus.yaml
    networks:
      - default
      - proxy
    deploy:
      labels:
        traefik.port: 9090
        traefik.frontend.rule: "Host:prometheus.localtest.me"
        traefik.docker.network: "proxy"

  volumes:
    gitlab_data:
      driver: local
      driver_opts:
        type: nfs4
        o: "addr=127.0.0.1"
        device: ":/gitlab-swarm/gitlab/data"
    gitlab_logs:
      driver: local
      driver_opts:
        type: nfs4
        o: "addr=127.0.0.1"
        device: ":/gitlab-swarm/gitlab/logs"
    gitlab_config:
      driver: local
      driver_opts:
        type: nfs4
        o: "addr=127.0.0.1"
        device: ":/gitlab-swarm/gitlab/config"

    postgres_data:
      driver: local
      driver_opts:
        type: nfs4
        o: "addr=127.0.0.1"
        device: :/gitlab-swarm/postgres
    prometheus_data:
      driver: local
      driver_opts:
        type: nfs4
        o: "addr=127.0.0.1"
        device: ":/gitlab-swarm/prometheus"

  configs:
    gitlab.rb:
      file: "./gitlab.rb"
    prometheus.yaml:
      file: "./prometheus.yaml"


  networks:
    proxy:
      external: true     