version: "3.8"

services:
  traefik:
    image: traefik:latest
    command: --providers.docker.swarmmode --api.dashboard=true --api.insecure=true --log.level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"

networks:
  proxy:
    external: true
