version: "3.4"

services:
  nginx:
    image: nginx:1.13.8-alpine
    configs:
      - source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - proxy
    ports:
      - "80:80"

configs:
  nginx.conf:
    file: ./nginx.conf

networks:
  proxy:
    external: true